// Code generated by MockGen. DO NOT EDIT.
// Source: adder.go

package gomock_ex

import (
	"reflect"

	"github.com/golang/mock/gomock"
)

// MockAdder is a mock of Adder interface.
type MockAdder struct {
	ctrl     *gomock.Controller
	recorder *MockAdderMockRecorder
}

// MockAdderMockRecorder is the mock recorder for MockAdder.
type MockAdderMockRecorder struct {
	mock *MockAdder
}

// NewMockAdder creates a new mock instance.
func NewMockAdder(ctrl *gomock.Controller) *MockAdder {
	mock := &MockAdder{ctrl: ctrl}
	mock.recorder = &MockAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdder) EXPECT() *MockAdderMockRecorder { return m.recorder }

// Sum mocks base method.
func (m *MockAdder) Sum(a, b int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sum", a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// Sum indicates an expected call of Sum.
func (mr *MockAdderMockRecorder) Sum(a, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockAdder)(nil).Sum), a, b)
}
